### ISSUE TITLE
Only show GPU usage and not the memory along with it

### ISSUE THREAD

**Issue by Pagla-Dasu** [PolpOnline/gpu-usage-waybar#2]
Hey, @PolpOnline , can we only show the GPU usage percentage and not the memory percentage too, I like it more clean, so I only want to show the GPU usage, is it possible, if it is can you show me, or enable this feature.

**Comment by Rolv-Apneseth** [comment]
I would also like this. Maybe just a flag to only show the GPU usage? The data being shown when hovering is nice though.

**Comment by PolpOnline** [comment]
Hi, sorry for replying late.
I just added a new flag, `--text-no-memory` that hides the memory info in the text part, which is the one displayed in the bar.
