### ISSUE TITLE
Change format

### ISSUE THREAD

**Issue by Rolv-Apneseth** [PolpOnline/gpu-usage-waybar#3]
Hi, cool project, thank you for making it.

I'm looking to change the `format` field on the custom widget to `"format": "{icon} {}",`, however, I'm getting the following error from waybar:

```
custom/gpu-usage: cannot switch from manual to automatic argument indexing
```

I'm not very familiar with how waybar works, but is this something that's fixable from this end?

**Comment by PolpOnline** [comment]
Hi, sorry for replying late, in my case using  `"format": "{icon} {0} {1}"` worked

**Comment by Rolv-Apneseth** [comment]
That does indeed work, thank you
